[project]
name = "hmepy"
version = "1.7.0"
dependencies = [
    "pandas",
    "numpy",
    "scikit-learn",
    "requests",
    "importlib-metadata",
    "matplotlib",
]

[tool.pytest.ini_options]
pythonpath = [
  "."
]