name: install-and-test

on: [push, pull_request]

jobs:
  install_and_test:
    # Set up operating system
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10']
    name: Install and Test
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install hmePy
        run: pip install -e .
      - name: Install Tests
        working-directory: ./tests
        run: pip install pytest pytest-cov pytest-xdist
      - name: Run All Tests
        working-directory: ./tests
        run: pytest *_test.py -n auto --durations=0
